### ISSUE TITLE
New gem release?

### ISSUE THREAD

**Issue by jgrau** [schneems/maildown#25]
Is it possible to release a new version based on the current master?

**Comment by schneems** [comment]
done

**Comment by jgrau** [comment]
I still see 2.0.0 (released January 2016) as the latest release...?

**Comment by jgrau** [comment]
Sorry to bug you about this again but I think something went awry with that gem release. I still see 2.0.0 as the latest release?

**Comment by schneems** [comment]
Updated https://rubygems.org/gems/maildown
